set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)

set(RISCV_TRIPLE riscv64-linux-gnu)

set(CMAKE_C_COMPILER   ${RISCV_TRIPLE}-gcc)
set(CMAKE_CXX_COMPILER ${RISCV_TRIPLE}-g++)
set(CMAKE_AR           ${RISCV_TRIPLE}-ar)
set(CMAKE_RANLIB       ${RISCV_TRIPLE}-ranlib)
set(CMAKE_STRIP        ${RISCV_TRIPLE}-strip)
set(CMAKE_NM           ${RISCV_TRIPLE}-nm)
set(CMAKE_OBJDUMP      ${RISCV_TRIPLE}-objdump)

set(CMAKE_FIND_ROOT_PATH /usr/${RISCV_TRIPLE})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_C_FLAGS_INIT   "-march=rv64gc -mabi=lp64d")
set(CMAKE_CXX_FLAGS_INIT "-march=rv64gc -mabi=lp64d")

set(CMAKE_EXE_LINKER_FLAGS_INIT    "-static")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "")

set(CMAKE_CROSSCOMPILING_EMULATOR "qemu-riscv64-static;-L;/usr/${RISCV_TRIPLE}")

set(CMAKE_INSTALL_PREFIX /usr/${RISCV_TRIPLE}/local CACHE PATH "" FORCE)

set(THREADS_PTHREAD_ARG 0 CACHE STRING "" FORCE)
set(HAVE_PTHREAD_ATFORK 0 CACHE STRING "" FORCE)
