set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)
set(CMAKE_SYSTEM_VERSION 1)

set(RISCV_TRIPLE riscv64-linux-gnu)
set(RISCV_SYSROOT /usr/${RISCV_TRIPLE})

find_program(RISCV_GCC     ${RISCV_TRIPLE}-gcc     REQUIRED)
find_program(RISCV_GXX     ${RISCV_TRIPLE}-g++     REQUIRED)
find_program(RISCV_AR      ${RISCV_TRIPLE}-ar      REQUIRED)
find_program(RISCV_RANLIB  ${RISCV_TRIPLE}-ranlib  REQUIRED)
find_program(RISCV_STRIP   ${RISCV_TRIPLE}-strip   REQUIRED)
find_program(RISCV_NM      ${RISCV_TRIPLE}-nm      REQUIRED)
find_program(RISCV_OBJDUMP ${RISCV_TRIPLE}-objdump REQUIRED)
find_program(RISCV_OBJCOPY ${RISCV_TRIPLE}-objcopy REQUIRED)

set(CMAKE_C_COMPILER   ${RISCV_GCC})
set(CMAKE_CXX_COMPILER ${RISCV_GXX})
set(CMAKE_ASM_COMPILER ${RISCV_GCC})
set(CMAKE_AR           ${RISCV_AR}      CACHE FILEPATH "" FORCE)
set(CMAKE_RANLIB       ${RISCV_RANLIB}  CACHE FILEPATH "" FORCE)
set(CMAKE_STRIP        ${RISCV_STRIP}   CACHE FILEPATH "" FORCE)
set(CMAKE_NM           ${RISCV_NM}      CACHE FILEPATH "" FORCE)
set(CMAKE_OBJDUMP      ${RISCV_OBJDUMP} CACHE FILEPATH "" FORCE)
set(CMAKE_OBJCOPY      ${RISCV_OBJCOPY} CACHE FILEPATH "" FORCE)

set(CMAKE_FIND_ROOT_PATH ${RISCV_SYSROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_SYSROOT "")

set(RISCV_MARCH "rv64gc")
set(RISCV_MABI  "lp64d")

set(RISCV_ARCH_FLAGS "-march=${RISCV_MARCH} -mabi=${RISCV_MABI}")
set(RISCV_SAFETY_FLAGS
    "-fno-stack-protector"
    "-fno-exceptions"
)

list(JOIN RISCV_SAFETY_FLAGS " " RISCV_SAFETY_FLAGS_STR)

set(CMAKE_C_FLAGS_INIT
    "${RISCV_ARCH_FLAGS} ${RISCV_SAFETY_FLAGS_STR} -O2"
    CACHE STRING "" FORCE
)
set(CMAKE_CXX_FLAGS_INIT
    "${RISCV_ARCH_FLAGS} ${RISCV_SAFETY_FLAGS_STR} -O2"
    CACHE STRING "" FORCE
)

set(RISCV_STATIC_FLAGS "-static -static-libgcc")
set(CMAKE_EXE_LINKER_FLAGS_INIT
    "${RISCV_STATIC_FLAGS}"
    CACHE STRING "" FORCE
)
set(CMAKE_SHARED_LINKER_FLAGS_INIT "" CACHE STRING "" FORCE)
set(CMAKE_MODULE_LINKER_FLAGS_INIT "" CACHE STRING "" FORCE)

find_program(QEMU_RISCV64 NAMES qemu-riscv64-static qemu-riscv64 REQUIRED)
set(CMAKE_CROSSCOMPILING_EMULATOR
    "${QEMU_RISCV64};-L;${RISCV_SYSROOT}"
    CACHE STRING "" FORCE
)

set(CMAKE_INSTALL_PREFIX
    ${RISCV_SYSROOT}/local
    CACHE PATH "" FORCE
)

set(THREADS_PTHREAD_ARG          "0"      CACHE STRING "" FORCE)
set(HAVE_PTHREAD_ATFORK          "0"      CACHE STRING "" FORCE)
set(CMAKE_HAVE_LIBC_PTHREAD      FALSE    CACHE BOOL   "" FORCE)
set(CMAKE_THREAD_LIBS_INIT       ""       CACHE STRING "" FORCE)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY CACHE STRING "" FORCE)

set(PKG_CONFIG_EXECUTABLE        ""       CACHE FILEPATH "" FORCE)
set(CMAKE_DISABLE_FIND_PACKAGE_PkgConfig TRUE CACHE BOOL "" FORCE)
